### ISSUE TITLE
Cant import panda_model

### ISSUE THREAD

**Issue by fjakob** [JeanElsner/panda_model#2]
When I try to import the panda_model_download function (or run it through the command line) the following error is yielded:

![Screenshot from 2023-02-13 17-52-05](https://user-images.githubusercontent.com/78848571/218520982-758be02c-c98e-4a40-870c-4443a1eb7ef2.png)

**Comment by JeanElsner** [comment]
Hi,
thanks for pointing this issue out to me. This was kind of specific to Ubuntu 20.04 and not caught by the unittests, but should be fixed now 629395b.
